---
title: "EPIB 678-001 Advanced health decision modelling"
subtitle: "Course syllabus, Winter 2026, McGill University"
format:
  html: 
    toc: true
  pdf:
    toc: true
editor: visual
---

```{=html}
<!--
Clicking"render" will only do the first format (html) and delete any other versions (pdf). 
To render both html and pdf, use 

quarto::quarto_render("syllabus/epid-678_syllabus.qmd") 



-->
```

## Course description

Developing decision-analytic models to synthesize evidence and simulate the outcomes of strategies in public health and medicine, including health technology assessment and model-based economic evaluation. Methodologies include cohort state transition modelling, microsimulation, discrete event simulation, Bayesian model calibration, probabilistic sensitivity analysis, value of information analysis, and equity-informative modelling frameworks. Applications include disease screening, prevention, and treatment, public health strategy, and prioritization of health research.

## Learning objectives

By the end of the course, students should be able to:

-   Develop decision analytic models to inform health policy and clinical decisions
-   Understand and critically appraise model-based decision analyses
-   Create transparent reports of model-based decision analyses that conform to open science principles

## Instructor

**W. Alton Russell, PhD**, Assistant Professor, McGill School of Population and Global Health. [alton.russell\@mcgill.ca](alton.russell@mcgill.ca) \| [mchi.mcgill.ca/decision-modelling-lab](mchi.mcgill.ca/decision-modeling-lab) \| Office: 2001 McGill College #1113

## Class meetings & office hours

**Class meetings** will be held 11:35am -- 12:55pm on Tuesdays and Thursdays at 2001 McGill College Ave in room #1128. Attendance is expected.

**Office hours** will be held 2:30pm – 3:30pm on Mondays at 2001 McGill College Ave in room #1203. Students can take advantage of office hours to discuss assignments, projects, and readings or ask general career/research questions. All students are encouraged to attend. Most discussions take place openly so that other students can listen in or join in. Students who would like a private discussion should let the instructor know.

## Target audience

The course is oriented towards PhD students and advanced Master's students interested in applying model-based analyses of health policies, decisions, or technologies in research. Modelling skills developed in the course will also be useful for students interested in industry or government roles related to economic evaluation, policy modelling, health technology assessment, or health economics and outcomes research.

## Prerequisites

The ideal preparation of this course includes (1) at least an introductory course in R or a similar programming language, (2) a course in probability, (3) a course in statistics. A course on economic evaluation such as PPHS 528 is not necessary but would provide helpful context. Prior experience programming in R is ideal, but students with solid experience in programming fundamentals (e.g., nested loops, functions, data structures) should be able to learn the R syntax and environment as they go. Students who lack a prerequisite other than programming may need to spend extra time on some course components but should be able to succeed in the course. Students without programming, or without training in either statistics or probability, should not take the course. To help make an informed decision on how well-prepared you are for the course, you may [attempt to complete assignment 0 early (available on Github)](https://github.com/altonrus/epib-676/tree/main/assignments).

## Readings

Readings drawn from various sources are assigned before most class sessions as indicated in the schedule below. PDFs of the readings are available on myCourses. Some readings are tutorials with accompanying code, which you are encouraged to download and run. To get full credit for class engagement, students should come to class prepared to discuss the readings.

If \>20 pages are assigned for a given class, students may skim some of the material, particularly readings that are marked as 'secondary.' But students should be sufficiently familiar with each reading to quickly find relevant material as they work on assignments and their project.

## Laptops and software

Students should bring a personal laptop to class. Please let the instructor know right away if this is a challenge so we can find a solution. Before the first session, students should install and configure the necessary software (R, RStudio, Quarto, git) [using the 'Setting up your software enviroment' instructions from session 1](https://htmlpreview.github.io/?https://github.com/altonrus/epib-676/blob/main/sessions/01-introduction/get-set-up.html).

## Approach to learning

The course provides hands-on experience applying course concepts early and often. The course has two phases with some overlap:

-   **The methods phase (15 sessions)** focuses on understanding methods and workflows and building programming skills. Readings are primarily pedagogical in nature, including tutorials with accompanied R code you can examine and run. Some class sessions will include running sample code on your own laptop. Six programming assignments will provide hands-on experience in coding a model-based decision analysis.
-   **The application phase (11 sessions)** focuses on the use of decision analytic modelling to inform health policy and clinical practice. Students will be assigned a diverse set of applied modelling analyses as readings and hear from a variety of decision-analytic modellers in class sessions. Students will also analyze and present an existing open-source modelling study. For the course project, students will develop their own model-based decision analysis.

## Assignments & evaluation

All assignments are to be completed individually. More information on the course project and presentation, including a detailed grading rubric, are available in the syllabus folder on the course Github site.

### Class engagement (8%)

+----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Students earn credit for class engagement by:                                                | Students' class engagement score may be reduced if:                                                                                                                 |
+==============================================================================================+=====================================================================================================================================================================+
| -   Attending class sessions on time                                                         | -   Students are tardy or absent from multiple sessions. Exceptions for valid reasons may be granted in advance. Medical emergencies may be excepted retroactively. |
+----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Engaging in discussions, having completed the assigned readings                          | -   Students engage (participate in discussion or ask a question) less than once every two class sessions                                                           |
+----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Listening attentively and following along with programming examples on their own laptops | -   Students often look at cell phones or engage in unrelated activities on their computers during class sessions                                                   |
+----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### R programming assignments (48%)

A series of time-intensive programming assignments will provide hands-on experience developing decision analytic modelling analyses. For each assignment, students will download a Zip file that contains a Quarto document from the [class Github site](https://github.com/altonrus/epib-676/tree/main/assignments). The Quarto document includes questions, instructions, and starter code. Students will complete the assignments by completing the code and answering questions. Once complete, students will render their Quarto document to an HTML file, which they upload to [myCourses](https://mycourses2.mcgill.ca/) for grading.

0.  Simpler models (8%)
1.  Decision trees, cost-effectiveness (8%)
2.  Cohort models (8%)
3.  Simulation (8%)
4.  Differential equation models & uncertainty analysis (8%)
5.  Calibration, validation, and value of information (8%)

[**Assessment:**]{.underline} Students who correctly complete all components of the assignments will receive full marks. Partial credit will be awarded for components that contain errors but demonstrate at least partial understanding of how to program the relevant modelling concept. Out of fairness to all classmates, late assignments will be penalized 20% per day unless an exception is granted more than 2 days before the deadline or under exceptional circumstances. All assignments will be available at least 10 days before their deadline. Students should:

-   Start early

-   Read the whole assignment before you begin and feel free to go out of order

-   Spend some time on it each day for 3 or more days (instead of completing it in one sitting)

-   Work alone first, then discuss with classmates and/or the instructor (but you must write your own code and responses)

-   Come to office hours to discuss

### Presentation of open-source modelling analysis (8%)

Students will find a published applied decision-analytic modelling analysis that includes code. Students will read the paper, analyze the approach to coding, attempt to run the model on their own machine, and give a brief in-class presentation about their experience.

### Course project (36%)

The default course project entails developing a decision-analytic model and use it to inform a decision from health policy or clinical practice. Students are encouraged to analyze a decision problem related to their own research and/or engage with domain experts outside the class when applicable. Other project topics, such as developing or assessing a novel method or using modelling methods for an application that is not a decision analysis, may be approved by the instructor on a case-by-case basic. Students are strongly encouraged to come to office hours to discuss their project with the instructor.

1.  Proposal (3%)
2.  Class presentation (8%)
3.  Written report (with code) (25%)

## Logistics

All readings are available to enrolled students in [myCourses](https://mycourses2.mcgill.ca/). Assignments are due at 11:59pm EST on the date indicated in the schedule below, to be uploaded on myCourses. Grades, feedback, and assignment solution will also be provided within myCourses. All other course materials are available on [Github](https://github.com/altonrus/epib-676), including the files needed to complete assignments.

## Academic integrity

McGill University values academic integrity. Therefore, all students must understand the meaning and consequences of cheating, plagiarism and other academic offences under the *Code of Student Conduct and Disciplinary Procedures* ([see here for more details](https://www.mcgill.ca/deanofstudents/students/student-rights-responsibilities/integrity)). Students found guilty of such academic offences will be given a failing grade to this course. 

## Use of generative AI

Students ***may not*** use GenAI tools like Chat-GPT or Copilot to complete programming assignments. For the course project, students ***may*** use GenAI for brainstorming ideas or to improve grammar and spelling. Students ***may not*** use GenAI tools to summarize or synthesize peer-reviewed literature, nor to develop the written language for their final report. Students who use GenAI for their project must describe any use of generative AI tools in their final written report.

## Language of submission

In accordance with McGill University's *Charter of Students' Rights*, students have the right to submit any written work that is to be graded in either English or French.

## Late enrollment

Students who enroll in the class after the first lecture should:

-   Watch all missed lecture recordings and complete the associated readings

-   Submit Assignment 0 on myCourses within one week of the first class they attend or by the deadline, whichever is later.

## Course schedule

+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**      | **Topics, Readings/tasks to be completed before class**                                                                                                                                                                                                                                 |
+===============+=========================================================================================================================================================================================================================================================================================+
| **6 Jan Tu**  | **1. Course introduction**                                                                                                                                                                                                                                                              |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Why do decision analysis                                                                                                                                                                                                                                                            |
|               | -   Analytic perspective                                                                                                                                                                                                                                                                |
|               | -   Using R and RStudio                                                                                                                                                                                                                                                                 |
|               | -   **Assignment 0 available (simpler models)**                                                                                                                                                                                                                                         |
|               |                                                                                                                                                                                                                                                                                         |
|               | (1) Follow the ['Setting up your software enviroment' instructions](https://htmlpreview.github.io/?https://github.com/altonrus/epib-676/blob/main/sessions/01-introduction/get-set-up.html) to make sure you have an up-to-date local version of R and Rstudio desktop on your laptop.\ |
|               | (2) Read through the [Hello, Quarto tutorial for RStudio](https://quarto.org/docs/get-started/hello/rstudio.html)                                                                                                                                                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **8 Jan Th**  | **2. Economic evaluation**                                                                                                                                                                                                                                                              |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Decision analytic frameworks                                                                                                                                                                                                                                                        |
|               | -   Quantifying health and costs                                                                                                                                                                                                                                                        |
|               | -   Incremental analysis                                                                                                                                                                                                                                                                |
|               | -   **Assignment 1 available (decision trees, cost-effectiveness)**                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                         |
|               | Ch. 1 'Introduction to health economic evaluation' from [Bayesian Methods in Health Economics (2012) by Gianluca Baio](https://doi.org/10.1201/b13099)\                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **13 Jan Tu** | **3. Probability, decision trees**                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Conditional probability                                                                                                                                                                                                                                                             |
|               | -   Distributions, expectation, variance                                                                                                                                                                                                                                                |
|               | -   Decision trees                                                                                                                                                                                                                                                                      |
|               | -   **Assignment 0 due Wednesday**                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                         |
|               | Ch 8 'Decision tree models' from [R for Health Technology Assessment August 2025 edition](https://gianluca.statistica.it/books/online/r-hta/chapters/08.decision_trees/decision-trees)\                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **15 Jan Th** | **4. Discete time cohort models I**                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Discrete time state-transition models                                                                                                                                                                                                                                               |
|               | -   Markov model solution                                                                                                                                                                                                                                                               |
|               | -   Time-varying transitions                                                                                                                                                                                                                                                            |
|               | -   **Assignment 2 available (cohort models)**                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Alarid Escudero et. al. 2022. An introductory tutorial on cohort state-transition models in R using a cost-effectiveness analysis example](https://doi.org/10.1177/0272989X221103163)\                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **20 Jan Tu** | **5. Discrete time cohort models II**                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Capturing health-economic outcomes                                                                                                                                                                                                                                                  |
|               | -   Discrete time error corrections                                                                                                                                                                                                                                                     |
|               | -   Capturing epidemiological outcomes                                                                                                                                                                                                                                                  |
|               | -   Differential equation models                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Alarid Escudero et. al. 2022. A tutorial on time-dependent cohort state-transition models in R using a cost-effectiveness analysis example](https://doi.org/10.1177/0272989X221121747)\                                                                                                |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 22 Jan Th     | **6. Workflow and good coding practices**                                                                                                                                                                                                                                               |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Open science practices                                                                                                                                                                                                                                                              |
|               | -   An R project workflow                                                                                                                                                                                                                                                               |
|               | -   Version control                                                                                                                                                                                                                                                                     |
|               | -   **Assignment 1 due Friday**                                                                                                                                                                                                                                                         |
|               | -   **Open-source model presentation assigned**                                                                                                                                                                                                                                         |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Alarid-Escudero et. al. 2019. A need for change! A coding framework for improving transparency in decision modelling](https://doi.org/10.1007/s40273-019-00837-x)                                                                                                                      |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 27 Jan Tu     | **7. Simulation I**                                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Monte Carlo simulation                                                                                                                                                                                                                                                              |
|               | -   Simulating decision trees                                                                                                                                                                                                                                                           |
|               | -   **Assignment 3 available (simulation)**                                                                                                                                                                                                                                             |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Krijkamp et. al. 2018. Microsimulation modelling for health decision sciences Using R: A tutorial](http://www.doi.org/10.1177/0272989X18754513)                                                                                                                                        |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **29 Jan Th** | **8. Simulation II**                                                                                                                                                                                                                                                                    |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Simulating state transition models                                                                                                                                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Discrete event simulation                                                                                                                                                                                                                                                           |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Simulating resource constraints                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   **Assignment 2 due Friday**                                                                                                                                                                                                                                                         |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Lopez-Mendez et. al. 2025. A Tutorial on Discrete Event Simulation Models in R Using a Cost-Effectiveness Analysis Example](https://doi.org/10.1101/2025.05.15.25327635)                                                                                                               |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **3 Feb Tu**  | **9. Simulation III**                                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Efficient coding strategies                                                                                                                                                                                                                                                         |
|               | -   Efficiency improvement for simulations                                                                                                                                                                                                                                              |
|               | -   Agent based models                                                                                                                                                                                                                                                                  |
|               | -   Network model models                                                                                                                                                                                                                                                                |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Chhatwal & He 2015. Economic evaluations with agent-based modelling: An introduction.](https://doi.org/10.1007/s40273-015-0254-2)                                                                                                                                                      |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **5 Feb Th**  | **10. Designing & parameterizing an analysis**                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Perspective, time horizons, comparators                                                                                                                                                                                                                                             |
|               | -   Deciding on scope & structure                                                                                                                                                                                                                                                       |
|               | -   Literature-based inputs                                                                                                                                                                                                                                                             |
|               | -   Patient-level data inputs                                                                                                                                                                                                                                                           |
|               | -   **Project proposal assigned**                                                                                                                                                                                                                                                       |
|               |                                                                                                                                                                                                                                                                                         |
|               | **Primary**: [*Roberts et. al. 2012. Conceptualizing a model: a report of the ISPOR-SMDM modelling Good Research Practices Task Force*](https://doi.org/10.1016/j.jval.2012.06.016)                                                                                                     |
|               |                                                                                                                                                                                                                                                                                         |
|               | **Secondary**: Ch 8 (pg 209 - 236) 'Finding and summarizing the evidence' from [*Decision Making in Health and Medicine (2014) by Hunink et. al.*](https://doi.org/10.1017/CBO9781139506779.011)                                                                                        |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **10 Feb Tu** | **11. Uncertainty analysis**                                                                                                                                                                                                                                                            |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Probabilistic sensitivity analysis                                                                                                                                                                                                                                                  |
|               | -   Credible intervals                                                                                                                                                                                                                                                                  |
|               | -   Univariate sensitivity analysis                                                                                                                                                                                                                                                     |
|               | -   Scenario analysis                                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Briggs et. al. 2012. Model parameter estimation and uncertainty analysis: ISPOR-SMDM modelling good practices task force report](https://doi.org/10.1177/0272989X12458348)                                                                                                             |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **12 Feb Th** | **12. Differential equations models**                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Intro to differential equations                                                                                                                                                                                                                                                     |
|               | -   Compartmental epidemic models                                                                                                                                                                                                                                                       |
|               | -   System dynamic models                                                                                                                                                                                                                                                               |
|               | -   Difference equation approximation                                                                                                                                                                                                                                                   |
|               | -   **Assignment 4 available (DEQ and Sensitivity analysis)**                                                                                                                                                                                                                           |
|               | -   **Assignment 3 due next Monday, Feb 16**                                                                                                                                                                                                                                            |
|               |                                                                                                                                                                                                                                                                                         |
|               | Reading TBD                                                                                                                                                                                                                                                                             |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **17 Feb Tu** | **13. Statistical models, causal inference, and decision-analytic modelling**                                                                                                                                                                                                           |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Time-to-event models                                                                                                                                                                                                                                                                |
|               | -   Competing events                                                                                                                                                                                                                                                                    |
|               | -   Temporal extrapolation                                                                                                                                                                                                                                                              |
|               |                                                                                                                                                                                                                                                                                         |
|               | **Primary:** [Kühne et. al. (2022). Causal evidence in health decision making: methodological approaches of causal inference and health decision science](https://doi.org/10.3205/000314)                                                                                               |
|               |                                                                                                                                                                                                                                                                                         |
|               | **Supplemental:** [Williams et. al. (2016). Cost-effectiveness analysis in R using a multi-state modelling survival analysis framework: A tutorial](https://doi.org/10.1177/0272989x16651869)                                                                                           |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **19 Feb Th** | **14. Calibration & validation**                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Bayesian model calibration                                                                                                                                                                                                                                                          |
|               | -   Model validation                                                                                                                                                                                                                                                                    |
|               |                                                                                                                                                                                                                                                                                         |
|               | **Primary:** [Menzies et. al. 2017. Bayesian methods for calibrating health policy models: A tutorial.](https://www.doi.org/10.1007/s40273-017-0494-4)                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                         |
|               | **Supplemental:** [Eddy et. al. 2012. Model transparency and validation: ISPOR-SMDM modelling good practices task force report](https://www.doi.org/10.1177/0272989X12454579)                                                                                                           |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **24 Feb Tu** | **15. Value of information analysis**                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   For research prioritization and as sensitivity analysis                                                                                                                                                                                                                             |
|               | -   VOI measures (EVPI, EVPPI, EVSI)                                                                                                                                                                                                                                                    |
|               | -   Challenges and limitations                                                                                                                                                                                                                                                          |
|               | -   **Assignment 4 due Wednesday**                                                                                                                                                                                                                                                      |
|               | -   **Assignment 5 available (calibration, validation, VoI)**                                                                                                                                                                                                                           |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Fenwick et. al. 2020. Value of information analysis for research decisions---an introduction: Report 1 of the ISPOR Value of Information Analysis Emerging Good Practices Task Force](https://doi.org/10.1016/j.jval.2020.01.001)                                                      |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **26 Feb Th** | **16. Equity and distributional considerations**                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   Evaluation frameworks                                                                                                                                                                                                                                                               |
|               | -   Estimating heterogeneity                                                                                                                                                                                                                                                            |
|               | -   **Project proposal due Friday**                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                         |
|               | [Killedar et. al. 2023, Modelled distributional cost-effectiveness analysis of childhood obesity interventions: A demonstration](https://doi.org/10.1007/s40258-023-00813-9)                                                                                                            |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | *Winter reading break March 2 to March 6, inclusive*                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **10 Mar Tu** | **17. Guest lecture 1**                                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **12 Mar Th** | **18. Student presentations of open-source modelling analyses**                                                                                                                                                                                                                         |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **17 Mar Tu** | **19. Guest lecture 2**                                                                                                                                                                                                                                                                 |
|               |                                                                                                                                                                                                                                                                                         |
|               | -   **Assignment 5 due Wednesday**                                                                                                                                                                                                                                                      |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **19 Mar Th** | **20. Guest lecture 3**                                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **24 Mar Tu** | **21. Guest lecture 4**                                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **26 Mar Th** | **22 Guest lecture 5**                                                                                                                                                                                                                                                                  |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **31 Mar Tu** | **23. Guest lecture 6**                                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **2 Apr Th**  | **24. Guest lecture 7**                                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **7 Apr Tu**  | **25. Guest lecture 8**                                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **9 Apr Th**  | **26. Project presentations and wrap-up lecture**                                                                                                                                                                                                                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **16 Apr Th** | Project report + code due on myCourses (no class)                                                                                                                                                                                                                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
